name: Fixed-Goal Grant Proposal
description: Submit a grant proposal for a project with a fixed goal
title: ""
labels: ["fixed goal"]
body:
  - type: textarea
    id: short_description
    attributes:
      label: Proposal description
      description: Please explain the essence of your proposal in 2-3 sentences. Include what the proposed changes are, and how it will benefit FreeCAD users, FreeCAD infrastructure, or the overall ecosystem.
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: |
        Please list all deliverables of your project. For each deliverable, please state:
        * Name/title of the change.
        * What will be delivered exactly? If it’s a user-visible change, what will users be able to do? If it’s a low-level change, what will it improve or make possible?
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: |
        Please provide a list of stages past the planning stage. For each stage please list:
        * Name of the stage
        * Estimated time to accomplish in hours
  - type: textarea
    id: risks_and_mitigation
    attributes:
      label: Risks and mitigation
      description: Please tell us about possible risks of not completing proposed work and how you plan to mitigate them. You don’t need to go public about details of your personal affairs, a summary will be sufficient, e.g. “Caring for a family member”, “Looking for full-time work while hacking on FreeCAD” etc.
  - type: textarea
    id: compensation
    attributes:
      label: Compensation
      description: How much you want for the project overall (in your local currency and its USD/EUR equivalent) How much you want per each stage (planning is a separate first stage)
  - type: textarea
    id: about_yourself
    attributes:
      label: About you
      description: |
        Please tell us about yourself
        * Name 
        * Forum / Community username(s)
        * Experience relevant to the proposed grant
        * Have you already contributed to FreeCAD? Please elaborate.
        * Have you ever worked on similar software before? Please elaborate.
        * Have you ever solved similar tasks before? Please elaborate.
