name: Funded grants list

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  update-issues-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up jq (for JSON processing)
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Get issues with funded label and store data in JSON
      run: |
        page=1
        all_issues="[]"

        while true; do
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/repos/${{ github.repository }}/issues?labels=funded&state=all&per_page=100&page=$page")
          if [ "$(echo $response | jq '. | length')" -eq 0 ]; then
            break
          fi
          all_issues=$(echo $all_issues $response | jq -s '[.[][]]')
          page=$((page + 1))
        done

        echo "$all_issues" > funded_grants_list_raw.json

    - name: Extract useful data (title, url, labels, creation date and author)
      run: |
        jq '[.[] | {title: .title, url: .html_url, labels: [.labels[].name], created_at: .created_at, author: .user.login}]' funded_grants_list_raw.json > funded_grants_list.json

    - name: Commit data to repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git add funded_grants_list.json
        git commit -m "Update funded grants list"
        git push
